### ISSUE TITLE
Move DatePicker.PersianCalendar project

### ISSUE THREAD

**Issue by Keboo** [Keboo/MaterialDesignInXaml.Examples#13]
This project should be moved inside of a folder called DatePicker to match how the rest of the projects are organized.
Ensure you also update the solution file so that it shows up in Visual Studio.

**Comment by RafaelGSS** [comment]
I did not understand... Create a root folder named DatePicker and insert all elements inside it? Or just elements like DatePicker.Example?

**Comment by Keboo** [comment]
@RafaelGSS create a folder at the root of the repository called "DatePicker" and move the existing DatePicker.PersionCalendar into it. Finally update the solution file to point to this new location for the project. Does that make sense?
