### ISSUE TITLE
how to  modify  code

### ISSUE THREAD

**Issue by fei-678** [Keboo/MaterialDesignInXaml.Examples#15]
Hello, I downloaded this file (Keboo / MaterialDesignInXaml.Examples)on github and opened it, there will be  errors. How do I modify it?thank  you

Unknown generation error "Unable to resolve the dependencies of assembly" Microsoft.Windows.Design.Extensibility, Version = 4.3.1.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a "because there is no preload. When using ReflectionOnly API, you must pass The ReflectionOnlyAssemblyResolve event preloads or loads dependent assemblies as needed. "MultiProject.Views

**Comment by Keboo** [comment]
Hi @fei-678 I am not able to replicate this issue. 

Many of the samples expect that you are using Visual Studio 2019. Some projects may also require that you [have .NET Core installed](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source). The exact requirements will vary from project to project. 

As for your exact error, I suspect that it was not able to restore NuGet packages. Can you pick on one of the projects and copy the text from the Output window for it?

**Comment by Keboo** [comment]
Closing for now unless there are further issues
