### ISSUE TITLE
The name "PopupBox" does not exist in the namespace "http://materialdesigninxaml.net/winfx/xaml/themes". 

### ISSUE THREAD

**Issue by fei-678** [Keboo/MaterialDesignInXaml.Examples#16]
Hello there. I download (Keboo / MaterialDesignInXamlToolkit-master (ZIP) )on the Github, unzip it open it, this error appears XDG0008: The name "PopupBox" does not exist in the namespace "http://materialdesigninxaml.net/winfx/xaml/themes". MaterialDesignDemo App.xaml
How do I solve this problem, thank you!

<Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="smtx:XamlDisplay">
                            <DockPanel>
                                <MaterialDesign:PopupBox DockPanel.Dock="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(materialDesignDemo:XamlDisplayEx.ButtonDock)}"
                                                         Padding="10" StaysOpen="True" HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                         VerticalAlignment="{TemplateBinding VerticalContentAlignment}" 
                                                         x:Name="PopupBox">
                                    <materialDesign:PopupBox.ToggleContent>
                                        <materialDesign:PackIcon Kind="Xml" Cursor="Hand" ToolTip="View XAML" 
                                                                 Foreground="{DynamicResource PrimaryHueDarkBrush}" 
                                                                 Background="Transparent" 
                                                                 Margin="3">

**Comment by Keboo** [comment]
XDG0008 is a designer issue. This appears to be a Visual Studio designer issue. Running the latest VS2019 preview builds it appears the designer issue has been fixed.
