### ISSUE TITLE
Where does the utilities reference come from ?

### ISSUE THREAD

**Issue by Xaalek** [Keboo/MaterialDesignInXaml.Examples#18]
Where does the utilities reference (in Menu.HorizonalDisplay) come from ? I don't get it when I install the materials design packages.

![image](https://user-images.githubusercontent.com/54487782/96738003-9174d880-13be-11eb-8b63-793d247260f3.png)

**Comment by Keboo** [comment]
It is a local project in this repo. You can see it [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Utilities/Utilities)

**Comment by Xaalek** [comment]
Ok so it's you who created the .dll right ?

**Comment by Keboo** [comment]
Yes that is correct. It is compiled from that project I linked above.

**Comment by Xaalek** [comment]
Ok thank you
