### ISSUE TITLE
Not   find  the  source : ValidationErrorTemplate.xaml   in the   (ValidationTemplate.MainWindow)  project（application）

### ISSUE THREAD

**Issue by fei-678** [Keboo/MaterialDesignInXaml.Examples#19]
```
<Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                **<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/ValidationErrorTemplate.xaml" />**
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>

```

                 **<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/ValidationErrorTemplate.xaml" />**
(ValidationTemplate.MainWindow)

        I tried to download the MahApps source code (Github) and I didn't find ::: "pack:,,,/MahApps.Metro; component/Styles/ValidationErrorTemplate.xaml".

**Comment by fei-678** [comment]
Hello.How I can to solved   the   problem?  Thank you!

**Comment by Keboo** [comment]
It looks like that sample broke with the latest NuGet update.
I have fixed that sample and adjusted the referenced template. You can find the MahApps source for the validation template [here](https://github.com/MahApps/MahApps.Metro/blob/9f7344170ba5ed7c04775b597c6edcb4efb7bfcc/src/MahApps.Metro/Styles/Controls.ValidationError.xaml).
