### ISSUE TITLE
cannot be found.   MaterialDesignTitleTextBlock  Resource 

### ISSUE THREAD

**Issue by fei-678** [Keboo/MaterialDesignInXaml.Examples#20]
Hello.
   System.Windows.Markup. The XamlParseException:"" in "System.Windows.StaticResourceExtension "An exception was raised when the value was provided on." The line number is "52" and the line position is "52"."

Exception: A resource named "MaterialDesignTitleTextBlock" cannot be found. Resource names are case sensitive.

`TextBlock Grid.Column="0" Grid.Row="0" Style="{StaticResource MaterialDesignTitleTextBlock}" `
Is there anything I can do to fix this problem?
Thank you.

**Comment by Keboo** [comment]
Thanks for letting me know. This was a [breaking change in the 3.0.0 release](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1301). I have updated the relevant projects renaming it to "MaterialDesignHeadline6TextBlock"
