### ISSUE TITLE
Outsourcing dialogs visual representaion 

### ISSUE THREAD

**Issue by wdefender** [Keboo/MaterialDesignInXaml.Examples#21]
Hi Keboo, is there a way to create the visual representation of dialogs in a separate file instead of embedding them directly into MainView as DialogContentTemplate? It does not seem to be right inside MainView if there are many dialogs. If yes, could you also provide an example (inside the project DialogHost.FromViewModel maybe?) how to outsource the visual representation? Thank you in advance. Your videos on youtube are very instructive, also thanks for that!

**Comment by Keboo** [comment]
Hi @wdefender  yes this is possible I just pushed a sample of this to the DialogHost.FromViewModel project. In short there are a few things you need to do to make this possible:
1. Give each distinct dialog its own view model type. This is done to make matching the dialog to a template possible. More details on that [here](https://docs.microsoft.com/dotnet/desktop/wpf/data/data-templating-overview?view=netframeworkdesktop-4.8#the-datatype-property)
2. Create `DataTemplate`s for each dialog in a `ResourceDictionary` (or multiple resource dictionaries if it helps with your project organization).
3. Reference the resource dictionary(ies) that contain your dialog's data template at the root of the XAML file that contains your dialog host. From your description it sounds like this will be MainView.xaml.

After that when you show one of the dialog's view models, it will look up the appropriate data template based on the type and use that to display it.

Hope that answers the question! Happy coding.
