### ISSUE TITLE
CustomLoginDialogTemplate.xaml references the wrong assembly

### ISSUE THREAD

**Issue by wdefender** [Keboo/MaterialDesignInXaml.Examples#22]
Hi Keboo, thank you very much for that instructive example how to move the visual representation of dialgohost.
But there is a small bug inside. CustomLoginDialogTemplate.xaml sholud reference **xmlns:system="clr-namespace:System;assembly=mscorlib"** and not **xmlns:system="clr-namespace:System;assembly=System.Runtime"**. Its not a big deal but it can be annoying for less experienced developers. Stay healthy and do well Keboo!

**Comment by Keboo** [comment]
@wdefender thanks for bringing this to my attention. Should be fixed now.
