### ISSUE TITLE
Button.CornerRadius example project

### ISSUE THREAD

**Issue by MichelMichels** [Keboo/MaterialDesignInXaml.Examples#27]
I was reviewing the Button.CornerRadius project and the code does something very clever in [MainWindow.xaml](https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/Button/Button.CornerRadius/MainWindow.xaml).

It changes a part of the button template with the attached property TreeHelpers.Modifiers. 

```xaml
<Style
    x:Key="SquareButton"
    TargetType="ButtonBase"
    BasedOn="{StaticResource MaterialDesignRaisedButton}">
    <Setter
        Property="utilities:TreeHelpers.Modifiers">
        <Setter.Value>
            <utilities:ModifierCollection>
                <utilities:Modifier
                    TemplatePartName="border"
                    Property="{x:Static Border.CornerRadiusProperty}">
                    <utilities:Modifier.Value>
                        <CornerRadius>0</CornerRadius>
                    </utilities:Modifier.Value>
                </utilities:Modifier>
            </utilities:ModifierCollection>
        </Setter.Value>
    </Setter>
</Style>
```

I think it's a genius bit of code, but I guess this is kinda legacy? There's ButtonAssist.CornerRadius now as an attached property on the button control itself.

My question is, should this code get dropped in favor of ButtonAssist.CornerRadius?

**Comment by Keboo** [comment]
Yea I think updating it to use the new attached property would be good. There are probably other sample that are in a similar state where latest updates in Material Design in XAML fix the need for the work arounds that are presented. I would actually be in favor of removing the sample altogether given that there are samples of using the CornerRadius properties in the Material Design Demo app.

**Comment by MichelMichels** [comment]
Seems indeed to drop it altogether. I just submitted a PR because I was already working on it. You can ignore that one.
