### ISSUE TITLE
Missing call NotifyCanExecuteChanged

### ISSUE THREAD

**Issue by karelit0** [Keboo/MaterialDesignInXaml.Examples#270]
https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/2398af401fd636cfdb1f22ec1b60229cd0813768/MVVM/MVVM.Validation/AttributeValidationViewModel.cs#L23

missing the call to notify the command to enable the button same on other properties and other ViewModel
```
set
{
	SetProperty(ref _FirstName, value);
	SubmitCommand.NotifyCanExecuteChanged();
}
```
after this change the example help me a lot, thanks for your hard work

**Comment by Keboo** [comment]
Thank you for pointing this out. Fixed
