### ISSUE TITLE
Update all projects to latest 2.5.0 release

### ISSUE THREAD

**Issue by Keboo** [Keboo/MaterialDesignInXaml.Examples#3]
Many projects reference MaterialDesignInXaml. All of these projects should be updated to the latest 2.5.0 release.

**Comment by zBrianW** [comment]
Was `MaterialDesignInXaml` meant to be `MaterialDesignThemes`, as i don't see any projects referencing MaterialDesignInXaml (and latest MaterialDesignThemes is 2.5.0.1205) ?

**Comment by elangovanr** [comment]
I'll take this.
