### ISSUE TITLE
problem of accessibility for property visibility

### ISSUE THREAD

**Issue by Frenchy62620** [Keboo/MaterialDesignInXaml.Examples#30]
in folder styling for the project TreeviewMenu in file MainWindow.xaml, i have an error about line 476

`<Setter Property="Visibility" Value="Hidden" />`

the property has a problem of accessibility or its unknown, i dont know how to avoid this error

regards
Terry

**Comment by Keboo** [comment]
Hi Terry,

I am not able to reproduce the issue. Are you able to post a screenshot of the failure. It would also be helpful to know if this error occurs when compiling or when running.

**Comment by Frenchy62620** [comment]
To precise, the error is just after compilation, but no problem to execute, its just a problem to display the xaml code in window 

the error avoid to display the different controls in the page.. Maybe its normal..but when i comment the line around the error no problem ....

Sorry for my poor english, hope you understand..

![error](https://user-images.githubusercontent.com/5192667/132643458-3a0e2306-f787-419a-9f91-f475dc79a6bb.png)

**Comment by Keboo** [comment]
I understand now. That is simply a designer error, not an actual WPF error. I will log an issue with Visual Studio for it.
